-- !Ups

INSERT INTO CountryDefinition (name) VALUES
('Afghanistan'),
('Albania'),
('Algeria'),
('Andorra'),
('Angola'),
('Anguilla'),
('Antarctica'),
('Antigua and Barbuda'),
('Saudi Arabia'),
('Argentina'),
('Armenia'),
('Aruba'),
('Australia'),
('Austria'),
('Azerbaijan'),
('Bahamas'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Belgium'),
('Belize'),
('Benin'),
('Bermuda'),
('Bhutan'),
('Belarus'),
('Myanmar [Burma]'),
('Bolivia'),
('Bosnia and Herzegovina'),
('Botswana'),
('Brazil'),
('Brunei'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Cape Verde'),
('Bonaire'),
('Chad'),
('Chile'),
('China'),
('Cyprus'),
('Colombia'),
('Comoros'),
('Republic of the Congo'),
('North Korea'),
('South Korea'),
('Kosovo'),
('Costa Rica'),
('Ivory Coast'),
('Croatia'),
('Cuba'),
('Curacao'),
('Denmark'),
('Dominica'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('United Arab Emirates'),
('Eritrea'),
('Estonia'),
('Ethiopia'),
('Fiji'),
('Philippines'),
('Finland'),
('France'),
('Gabon'),
('Gambia'),
('Georgia'),
('South Georgia and the South Sandwich Islands'),
('Germany'),
('Ghana'),
('Jamaica'),
('Japan'),
('Gibraltar'),
('Djibouti'),
('Jordan'),
('Greece'),
('Grenada'),
('Greenland'),
('Guadeloupe'),
('Guam'),
('Guatemala'),
('Guernsey'),
('French Guiana'),
('Guinea'),
('Equatorial Guinea'),
('Guinea-Bissau'),
('Guyana'),
('Haiti'),
('Honduras'),
('Hong Kong'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Ireland'),
('Iceland'),
('Bouvet Island'),
('Norfolk Island'),
('Christmas Island'),
('Isle of Man'),
('Cayman Islands'),
('Cocos [Keeling] Islands'),
('Cook Islands'),
('Falkland Islands'),
('Faroe Islands'),
('Heard Island and McDonald Islands'),
('Northern Mariana Islands'),
('Marshall Islands'),
('Solomon Islands'),
('Turks and Caicos Islands'),
('U.S. Virgin Islands'),
('British Virgin Islands'),
('U.S. Minor Outlying Islands'),
('Åland'),
('Israel'),
('Italy'),
('Jersey'),
('Kazakhstan'),
('Kenya'),
('Kyrgyzstan'),
('Kiribati'),
('Kuwait'),
('Laos'),
('Lesotho'),
('Latvia'),
('Lebanon'),
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Macao'),
('Macedonia'),
('Madagascar'),
('Malawi'),
('Maldives'),
('Malaysia'),
('Mali'),
('Malta'),
('Morocco'),
('Martinique'),
('Mauritania'),
('Mauritius'),
('Mayotte'),
('Mexico'),
('Micronesia'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montenegro'),
('Montserrat'),
('Mozambique'),
('Namibia'),
('Nauru'),
('Nepal'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('Niue'),
('Norway'),
('New Caledonia'),
('New Zealand'),
('Oman'),
('Netherlands'),
('Pakistan'),
('Palau'),
('Palestine'),
('Panama'),
('Papua New Guinea'),
('Paraguay'),
('Peru'),
('Pitcairn Islands'),
('French Polynesia'),
('Poland'),
('Portugal'),
('Puerto Rico'),
('Qatar'),
('United Kingdom'),
('Czechia'),
('Central African Republic'),
('Democratic Republic of the Congo'),
('Dominican Republic'),
('Romania'),
('Rwanda'),
('Russia'),
('Réunion'),
('Western Sahara'),
('Saint Kitts and Nevis'),
('Saint Martin'),
('Saint Pierre and Miquelon'),
('Saint Vincent and the Grenadines'),
('Samoa'),
('American Samoa'),
('Saint Barthélemy'),
('San Marino'),
('Saint Lucia'),
('Saint Helena'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leone'),
('Singapore'),
('Sint Maarten'),
('Syria'),
('Slovakia'),
('Slovenia'),
('Somalia'),
('Spain'),
('Sri Lanka'),
('United States'),
('South Africa'),
('Sudan'),
('South Sudan'),
('Suriname'),
('Svalbard and Jan Mayen'),
('Sweden'),
('Switzerland'),
('Swaziland'),
('São Tomé and Príncipe'),
('Tajikistan'),
('Taiwan'),
('Tanzania'),
('French Southern Territories'),
('British Indian Ocean Territory'),
('Thailand'),
('East Timor'),
('Togo'),
('Tokelau'),
('Tonga'),
('Trinidad and Tobago'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Tuvalu'),
('Ukraine'),
('Uganda'),
('Hungary'),
('Uruguay'),
('Uzbekistan'),
('Vanuatu'),
('Vatican City'),
('Venezuela'),
('Vietnam'),
('Wallis and Futuna'),
('Yemen'),
('Zambia'),
('Zimbabwe');

-- !Downs
DELETE FROM CountryDefinition;